/*
	iRfRgServiceExample.m
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import "iRfRgServiceExample.h"
#import "iRfRgService.h"

@implementation iRfRgServiceExample

- (void)run {
	// Create the service
	iRfRgService* service = [iRfRgService service];
	service.logging = YES;
	// service.username = @"username";
	// service.password = @"password";
	

	// Returns NSString*. 
	[service doReqComfirm:self action:@selector(doReqComfirmHandler:) username: @"" password: @"" jsonArray: @""];

	// Returns NSString*. 
	[service doRg:self action:@selector(doRgHandler:) username: @"" password: @"" splid: @"" rgqty: @"" locno: @""];

	// Returns NSString*. 
	[service doTr:self action:@selector(doTrHandler:) username: @"" password: @"" pkvalue: @"" jsonConfig: @""];

	// Returns NSString*. 
	[service getAllRg:self action:@selector(getAllRgHandler:) username: @"" password: @"" queryjson: @""];

	// Returns NSString*. 
	[service getAllRgGroupJSON:self action:@selector(getAllRgGroupJSONHandler:) username: @"" password: @"" queryjson: @""];

	// Returns NSString*. 
	[service getAllRgGroupXML:self action:@selector(getAllRgGroupXMLHandler:) username: @"" password: @"" queryxml: @""];

	// Returns NSString*. 
	[service getReqInfo:self action:@selector(getReqInfoHandler:) username: @"" password: @""];

	// Returns NSString*. 
	[service getRg:self action:@selector(getRgHandler:) username: @"" password: @"" labelno: @""];

	// Returns iRfRet*. 
	[service getRgs:self action:@selector(getRgsHandler:) queryxml: @"" code: @""];

	// Returns NSString*. 
	[service getStockByLoc:self action:@selector(getStockByLocHandler:) username: @"" password: @"" locno: @""];

	// Returns NSString*. 
	[service getTrGds:self action:@selector(getTrGdsHandler:) username: @"" password: @"" page: 0];

	// Returns NSString*. 
	[service mvConfirm:self action:@selector(mvConfirmHandler:) username: @"" password: @"" jsonObject: @""];

	// Returns NSString*. 
	[service queryJSON:self action:@selector(queryJSONHandler:) sql: @"" dbname: @""];

	// Returns NSString*. 
	[service queryXML:self action:@selector(queryXMLHandler:) sql: @"" dbname: @""];

	// Returns iRfRet*. 
	[service setEdisRg:self action:@selector(setEdisRgHandler:) xml: @""];

	// Returns id. 
	[service setIRfSetting:self action:@selector(setIRfSettingHandler:) username: @"" password: @"" jsonObject: @""];

	// Returns iRfRet*. 
	[service setRgSuccess:self action:@selector(setRgSuccessHandler:) ids: [NSMutableArray array] code: @""];

	// Returns NSString*. 
	[service test:self action:@selector(testHandler:) username: @"" password: @""];
}

	

// Handle the response from doReqComfirm.
		
- (void) doReqComfirmHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"doReqComfirm returned the value: %@", result);
			
}
	

// Handle the response from doRg.
		
- (void) doRgHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"doRg returned the value: %@", result);
			
}
	

// Handle the response from doTr.
		
- (void) doTrHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"doTr returned the value: %@", result);
			
}
	

// Handle the response from getAllRg.
		
- (void) getAllRgHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"getAllRg returned the value: %@", result);
			
}
	

// Handle the response from getAllRgGroupJSON.
		
- (void) getAllRgGroupJSONHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"getAllRgGroupJSON returned the value: %@", result);
			
}
	

// Handle the response from getAllRgGroupXML.
		
- (void) getAllRgGroupXMLHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"getAllRgGroupXML returned the value: %@", result);
			
}
	

// Handle the response from getReqInfo.
		
- (void) getReqInfoHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"getReqInfo returned the value: %@", result);
			
}
	

// Handle the response from getRg.
		
- (void) getRgHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"getRg returned the value: %@", result);
			
}
	

// Handle the response from getRgs.
		
- (void) getRgsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the iRfRet* result
		iRfRet* result = (iRfRet*)value;
	NSLog(@"getRgs returned the value: %@", result);
			
}
	

// Handle the response from getStockByLoc.
		
- (void) getStockByLocHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"getStockByLoc returned the value: %@", result);
			
}
	

// Handle the response from getTrGds.
		
- (void) getTrGdsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"getTrGds returned the value: %@", result);
			
}
	

// Handle the response from mvConfirm.
		
- (void) mvConfirmHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"mvConfirm returned the value: %@", result);
			
}
	

// Handle the response from queryJSON.
		
- (void) queryJSONHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"queryJSON returned the value: %@", result);
			
}
	

// Handle the response from queryXML.
		
- (void) queryXMLHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"queryXML returned the value: %@", result);
			
}
	

// Handle the response from setEdisRg.
		
- (void) setEdisRgHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the iRfRet* result
		iRfRet* result = (iRfRet*)value;
	NSLog(@"setEdisRg returned the value: %@", result);
			
}
	

// Handle the response from setIRfSetting.
		
- (void) setIRfSettingHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the id result
		id result = (id)value;
	NSLog(@"setIRfSetting returned the value: %@", result);
			
}
	

// Handle the response from setRgSuccess.
		
- (void) setRgSuccessHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the iRfRet* result
		iRfRet* result = (iRfRet*)value;
	NSLog(@"setRgSuccess returned the value: %@", result);
			
}
	

// Handle the response from test.
		
- (void) testHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"test returned the value: %@", result);
			
}
	

@end
		