/*
	iRfRgServiceExample.m
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import "iRfRgServiceExample.h"
#import "iRfRgService.h"

@implementation iRfRgServiceExample

- (void)run {
	// Create the service
	iRfRgService* service = [iRfRgService service];
	service.logging = YES;
	// service.username = @"username";
	// service.password = @"password";
	

	// Returns NSString*. 
	[service doRg:self action:@selector(doRgHandler:) username: @"" password: @"" splid: @"" rgqty: @"" locno: @""];

	// Returns NSString*. 
	[service doTr:self action:@selector(doTrHandler:) username: @"" password: @"" ugoodsid: @"" goodsname: @"" goodstype: @"" tradename: @"" factno: @"" goodsunit: @"" cusgdsid: @"" multi: @""];

	// Returns NSString*. 
	[service getAllRg:self action:@selector(getAllRgHandler:) username: @"" password: @""];

	// Returns NSString*. 
	[service getRg:self action:@selector(getRgHandler:) username: @"" password: @"" labelno: @""];

	// Returns iRfRet*. 
	[service getRgs:self action:@selector(getRgsHandler:) queryxml: @"" code: @""];

	// Returns NSString*. 
	[service getTrGds:self action:@selector(getTrGdsHandler:) username: @"" password: @"" page: 0];

	// Returns NSString*. 
	[service queryJSON:self action:@selector(queryJSONHandler:) sql: @"" dbname: @""];

	// Returns NSString*. 
	[service queryXML:self action:@selector(queryXMLHandler:) sql: @"" dbname: @""];

	// Returns iRfRet*. 
	[service setRgSuccess:self action:@selector(setRgSuccessHandler:) ids: [NSMutableArray array] code: @""];
}

	

// Handle the response from doRg.
		
- (void) doRgHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"doRg returned the value: %@", result);
			
}
	

// Handle the response from doTr.
		
- (void) doTrHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"doTr returned the value: %@", result);
			
}
	

// Handle the response from getAllRg.
		
- (void) getAllRgHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"getAllRg returned the value: %@", result);
			
}
	

// Handle the response from getRg.
		
- (void) getRgHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"getRg returned the value: %@", result);
			
}
	

// Handle the response from getRgs.
		
- (void) getRgsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the iRfRet* result
		iRfRet* result = (iRfRet*)value;
	NSLog(@"getRgs returned the value: %@", result);
			
}
	

// Handle the response from getTrGds.
		
- (void) getTrGdsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"getTrGds returned the value: %@", result);
			
}
	

// Handle the response from queryJSON.
		
- (void) queryJSONHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"queryJSON returned the value: %@", result);
			
}
	

// Handle the response from queryXML.
		
- (void) queryXMLHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"queryXML returned the value: %@", result);
			
}
	

// Handle the response from setRgSuccess.
		
- (void) setRgSuccessHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the iRfRet* result
		iRfRet* result = (iRfRet*)value;
	NSLog(@"setRgSuccess returned the value: %@", result);
			
}
	

@end
		